export const Grade: { [key: string]: string } = {
    HyogaijiFormerJinmeiyoCandidate: "Hyogaiji (former Jinmeiyō candidate)",
    HyogaijiFormerJoyoCandidate: "Hyogaiji (former Jōyō candidate)",
    HyogaijiToleratedJoyoVariant: "Hyogaiji (tolerated Jōyō variant)",
    JinmeiyoFormerJoyoKanji: "Jinmeiyō (former Jōyō kanji)",
    JinmeiyoTraditionalVariantOfJinmeiyo: "Jinmeiyō (traditional variant of Jinmeiyō)",
    JinmeiyoTraditionalVariantOfJoyo: "Jinmeiyō (traditional variant of Jōyō)",
    JinmeiyoUsedInNames: "Jinmeiyō (used in names)",
    Joyo1stGradeJuniorHighSchool: "Jōyō (1st grade of junior high school)",
    Joyo2ndGradeJuniorHighSchool: "Jōyō (2nd grade of junior high school)",
    Joyo3rdGradeJuniorHighSchool: "Jōyō (3rd grade of junior high school)",
    JoyoHighSchool: "Jōyō (high school)",
    KyoikuJoyo1stGradePrimarySchool: "Kyōiku-Jōyō (1st grade of primary school)",
    KyoikuJoyo2ndGradePrimarySchool: "Kyōiku-Jōyō (2nd grade of primary school)",
    KyoikuJoyo3rdGradePrimarySchool: "Kyōiku-Jōyō (3rd grade of primary school)",
    KyoikuJoyo4thGradePrimarySchool: "Kyōiku-Jōyō (4th grade of primary school)",
    KyoikuJoyo5thGradePrimarySchool: "Kyōiku-Jōyō (5th grade of primary school)",
    KyoikuJoyo6thGradePrimarySchool: "Kyōiku-Jōyō (6th grade of primary school)",
    KyujitaiHyogaiji: "Kyūjitai-Hyōgaiji"
}